name: Deploy Lambda Function
on:
  push:
    branches:
      - main # Adjust this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Change to your preferred Node.js version

      - name: Install dependencies
        run: yarn install # Adjust the command if you use Yarn

      - name: Deploy Lambda function
        env:
          AWS_REGION: us-east-2 # Replace with your AWS region (e.g., us-east-1)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # npm run build # Adjust the build command if needed
          aws lambda update-function-code --function-name candles-cleaner --zip-file fileb://package.zip
          # The above command assumes that your build output is in a 'lambda' directory and contains a 'package.zip' file
